name: CI

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: npm install
            - run: npm run drygen
            - run: npm test
            - run: npm run build

    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: npm install
            - run: npm run format
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Format by Prettier
